<style>
.red_text { color:red;}
</style>
<h2>Chapter 16: Critical Selling<span id="expand-all-16" class="expand-text expand-all">Expand</span></h2>
<ul class="chapter">
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Critical Selling: How Top Performers Accelerate the Sales Process and Close More Deals</div>
      <div style="display:none;" class="section_data">
         <p>In order to assist you in accurately determining the lead status and completing the Store Qualification Fields, we have prepared this schematic outlining the Hot Lead Qualification Process:</p>
          <img src="http://www.vapornation.com/prodguide/images/learning_center/hot-lead-chart.png">
          <p>Thus, the Hot Lead (HL) process can be broken up into three stages.</p> 
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Stage 1</div>
      <div style="display:none;" class="section_data">
      <p>Within the first <b>5 hours</b> following the assignment (unless the assignment is made after 8pm in which case 5 hours from 8am the following day), AEs have to contact the HL .</p>
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Stage 2</div>
      <div style="display:none;" class="section_data">
      <p>Within <b>14 day</b> periods (“shortened sales cycle”), the AE is expected to convert the lead into a customer.</p>
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Stage 3</div>
      <div style="display:none;" class="section_data">
      <p>If at the end of the <b>14 day</b> period a sale is <b>NOT</b> made, the AE is expected to have completely filled out  the mandatory fields contained within the Store Qualification section of the lead record in Zoho  and determine a Lead Status by following the guidelines below:</p>
      <h3>Scenario 1: Contact is not made</h3>
      <p>AE leaves a voice mail.   Thereafter, the AE is expected to email the customer and call again within 24 to 48 hours.   In this case, adjusts the Viability field to “Unable to contact” and Lead Status to “Requalify.”</p>
      <h3>Scenario 2: Contact is made, but a sale is NOT made</h3>
      <p>AE completes the mandatory Store Qualification fields (marked in Red) and adjusts the Lead Status to “Hot,” “Active,” “Reassign,” or “Dead.”</p>
      <p>The table below would guide you as to the appropriate selection:</p>
      <table border="1" cellpadding="10">
      <tr>
         <th>Lead Status</th>
         <th>Definition</th>
         <th>Fields and Appropriate Answers</th>
      </tr>
      <tr>
         <td>Hot</td>
         <td>The order is imminent (within <b>21 days</b>) from the date of assignment.</td>
         <td>
         <ul>
            <li><span class="red_text">Viability</span> –" Open, operating and selling vaporizers" or "Opening in near future"</li>
            <li><span class="red_text">Is order imminent?</span> - "Yes"</li>
            <li><span class="red_text">Name of Person Spoken to</span> – Enter name here</li>
            <li><span class="red_text">Expected Order Date</span> – Choose from a pick list.</li>
            <li><span class="red_text">Share of inventory dedicated to vaporizers</span> – Choose from a pick list</li>
            <li><span class="red_text">Type of vaporizers sold</span> – Choose from a pick list</li>
            <li><span class="red_text">No. of Locations</span> – Choose from a pick list</li>
         </ul>
         </td>
      </tr>
      <tr>
         <td>Active</td>
         <td>The order is <b>not</b> imminent but likely.</td>
         <td>
            <ul>
               <li><span class="red_text">Viability</span> –" Open, operating and selling vaporizers" or "Opening in near future"</li>
               <li><span class="red_text">Is order imminent?</span> - "No"</li>
               <li><span class="red_text">Name of Person Spoken to</span> – Choose from a pick list</li>
               <li><span class="red_text">Share of inventory dedicated to vaporizers</span> – Choose from a pick list</li>
               <li><span class="red_text">Type of vaporizers sold</span> – Choose from a pick list</li>
               <li><span class="red_text">No. of Locations</span> –Choose from a pick list </li>
            </ul>
         </td>
      </tr>
      <tr>
         <td>Dead</td>
         <td>AE confirms that store is closed or no potential for selling vapes in the foreseeable future.</td>
         <td><uL><li><span class="red_text">Viability</span> – "Closing or closed"</li></ul></td>
      </tr>
      <tr>
      	<td>Reassign</td>
         <td>AE confirms that the store is OPEN and OPERATING but does not feel he/she is a good fit with the prospect.</td>
         <td>
         <ul>
            <li><span class="red_text">Viability</span> –"Open, operating and selling vaporizers" or "Opening in near future"</li>
            <li><span class="red_text">Is order imminent?</span> - "No"</li>
            <li><span class="red_text">Name of Person Spoken to</span> – Enter name here</li>
            <li><span class="red_text">Share of inventory dedicated to vaporizers</span> – Choose from a pick list</li>
            <li><span class="red_text">Type of vaporizers sold</span> – Choose from a pick list</li>
            <li><span class="red_text">No. of Locations</span> – Choose from a pick list</li>
            <li><span class="red_text">** AE MUST provide a detailed note in Zoho explaining why this needs to be reassigned.</span></li>
         </ul>
         </td>
      </tr>
      </table>
      <p>The <span class="red_text">Hot Leads to Qualify</span> view in Zoho has been created for you to keep track of your progress.  Any leads that are included in this view require your continuing attention.   Note that you can sort by the <span class="red_text">Hot Lead Assigned Time</span> Column so you know which hot lead has been assigned to you first.</p>
      <p><span class="red_text">14 Days Rule</span></p>
      <p>If ALL of these required fields (in Red) are not completed within the 14 day period, the CRM will alert us to reassign the lead.  If this occurs, <span class="red_text">you may not be assigned ANY Hot leads for 30 days.</span></p>
      <p>If it is discovered that these fields are not accurately completed (i.e., just completing them to fulfil the requirement), we will impose harsh disciplinary consequences, including possible termination of employments.</p>
      </div>
   </li>
   <li>
   	<div class="quiz-link-outer"><a href="http://www.vapornation.com/prodguide/learning-center/quiz?chapter=16" class="quiz-link">Click Here to Take the Chapter Sixteen Quiz</a></div>
   </li>
</ul>