<h2>Chapter 15: ZOHO (Hot Lead Management Process)<span id="expand-all-15" class="expand-text expand-all">Expand</span></h2>

<ul class="chapter">
   <li>
   	<div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Summary</div>
      <div style="display:none;" class="section_data">
         <p>Hot lead management process manual was created to assist AEs in efficiently qualifying their assigned hot leads and secure orders within 14 days. Here is the outline of the manual.
            <ol>
               <li>Outline of Hot Lead Management Process</li>
               <li>Store Qualification Section Details</li>
               <li>Hot Lead Management Audit</li>
            </ol>
         </p>
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Outline of Hot Lead Management Process</div>
      <div style="display:none;" class="section_data">
       <img src="http://www.vapornation.com/prodguide/images/learning_center/hot-lead-chart.jpg">
         
         <h3>Hot Lead (HL) process can be broken up into three stages.</h3>
			<ol>
            <li>Contact lead inquiry within <b>5 hours</b> of assigned time. (If assigned after 8pm, clock will begin at 8am of the next business day) The Account Executive (AE) has <b>5 hours</b> to contact the HL after the customer's initial inquiry.</li>
            <li>Obtain Sales Order within <b>14 days</b> of the customer’s initial inquiry.The AE is expected to convert the lead into a customer(Account) by obtaining an order. ("Shortened sales cycle")</li>
            <li>If, at the end of the <b>14 day period</b>, a <u>SALE IS NOT MADE</u>, 
   The AE is expected to have filled in the appropriate mandatory fields in "Store Qualification" details section in Zoho
   and update the Lead Status by following the guide on page 3.</li>
         </ol>
         <p>In this example, we have a viable lead, with contact name, but order is not imminent so Lead Status needs to be changed to active)</p>
         <img src="http://www.vapornation.com/prodguide/images/learning_center/store-qualification.png">
         
   	</div>
   </li>
   <li>
   <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Viability Options</div>
      <div style="display:none;" class="section_data">
      	<img src="http://www.vapornation.com/prodguide/images/learning_center/viability-option.png">
         <ol>
         <li>
         <u>Is order imminent?</u><br>
         <img src="http://www.vapornation.com/prodguide/images/learning_center/order-imminent.png">
         </li>
         <li>
         <u>Share of Inventory Dedicated to Vaporizers.</u><br>
         <img src="http://www.vapornation.com/prodguide/images/learning_center/share.png">
         </li>
         <li>
         <u>Types of Vaporizers Sold</u><br>
          <img src="http://www.vapornation.com/prodguide/images/learning_center/type-sold.png">
         </li>
         </ol>
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Hot Lead to Qualify</div>
      <div style="display:none;" class="section_data">
         <p>AEs need to navigate to "Hot Lead to Qualify" view in Zoho, as illustrated below and sort the "Hot Lead Assigned Time" column by descending order; this will allow the AE to focus on working Hot Leads that are reaching the end of their 14 day cycle. Hot leads that are presented in this view represent pending action(s) and or missing field(s).</p>
         <img src="http://www.vapornation.com/prodguide/images/learning_center/hot-leads.png">
      </div>
   </li>
   <li>
   <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Scenario 1: Contact is not made</div>
   <div style="display:none;" class="section_data">
      <p><u>Required actions:</u></p>
      <ol type="a">
         <li>AEs have to leave voice mail</li>
         <li>AE is expected to email the customer and also follow up again with them within 24 to 48 hours.</li>
         <li>Adjusting to the Viability fields to "Unable to contact", and Lead status to "Requalify"</li>
      </ol>
   </div>
   </li>
   <li>
   <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Scenario 2: Contact is made, <u>BUT A SALE IS NOT MADE</u></div>
      <div style="display:none;" class="section_data">
      <p><u>Required actions:</u></p>
         <ol type="a">
            <li>Fill out fields in Store Qualification (mandatory fields are in Red), and assign appropriate Lead Status "Hot", "Active" or "Dead"</li>
            <li>The table below would guide AEs to correctly fill out fields, and assign Lead Status as Hot, Active, Dead or Reassign.</li>
         </ol>
      </div>
   </li>
   
   <li>
   <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>III. Hot Lead Management Audit</div>
      <div style="display:none;" class="section_data">
      <p>Hot leads qualification management audit will be conducted by Operations to ensure that both <b>5 hour</b> initial contact and <b>14 day order compliance</b> are met. The goal is to ensure a timely response via phone (preferably) or email to wholesale inquiries. Validations for fields that are required have been set up through tracking via Zoho reporting. Calls will be verified by Shoretel and confirmed by way of reaching out to each inquiry by phone and conducting a customer survey. Any failures to meet requirements will result in suspension of new leads for periods ranging from 1- 3 months and or disciplinary action.</p>
      </div>
   </li>   
	<li>
   	<div class="quiz-link-outer"><a href="http://www.vapornation.com/prodguide/learning-center/quiz?chapter=15" class="quiz-link">Click Here to Take the Chapter Fifteen Quiz</a></div>
   </li>
</ul>