<h2>Chapter 10: Ecstacy Herbal Cigarettes <span id="expand-all-10" class="expand-text expand-all">Expand</span></h2>
<ul class="chapter">
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>What are Ecstacy Herbal Cigarettes?</div>
      <div style="display:none;" class="section_data">
         <p>Ecstacy Herbal Cigarettes contain a unique blend of all-natural herbs that are 100% tobacco and nicotine free. Their mixture of soothing herbal blends is a terrific substitute for tobacco and great for anyone looking to quit smoking. Herbal smokes provide a healthier alternative without the addictive properties of nicotine that are associated with traditional tobacco cigarettes.</p>
         <p>Ecstacy Herbal Cigarettes are a safer and healthier substitute for standard tobacco products as there is absolutely no nicotine or tobacco. These herbal smokes are also great in aiding smoking cessation because they contain zero nicotine – the addictive ingredient found inside most tobacco cigarettes.</p>
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Who Smokes Herbal Cigarettes?</div>
      <div style="display:none;" class="section_data">
         <p>In addition to being used as a tool to help people quit smoking, herbal cigarettes have also been gaining popularity in recent years among film, television and theatre companies as props or substitutes for actual cigarettes. They’re not exactly fake cigarettes, but they are a viable substitute for nicotine cigarettes because they do not emit any noxious odor or toxic secondhand smoke. This means they are safe to be burned in any theatre or soundstage.</p>         
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>What Ingredients are in Ecstacy Herbal Cigarettes?</div>
      <div style="display:none;" class="section_data">
         <p>Ecstasy Herbal Cigarettes may contain one or more of the following herbal and other natural ingredients: Marshmallow Leaf, Rose Petals, Red Clover, Clove Powder, Licorice, Wild Lettuce, Sage, Apple Juice, Honey, Acetic Acid, and Vanilla Liquid.</p>         
      </div>
   </li>
   <li>
      <div class="section_title"><span class="arrow" style="padding-right:20px;">&#x25BC;</span>Types of Ecstacy Herbal Cigarettes</div>
      <div style="display:none;" class="section_data">      
      <p><b>Whites:</b></p>
      <div style="text-align:center;"><img src="http://www.ecstacycigarettes.com/skin/frontend/default/mt_beca/images/new_homepage/whites_icon.jpg"></div>       
      <p>Ecstacy White Cigarettes feature a unique blend of natural herbs which provide the smoker with a lighter, more traditional tobacco-like flavor and aroma.</p>      
      <p><b>Reds:</b></p>
      <div style="text-align:center;"><img src="http://www.ecstacycigarettes.com/skin/frontend/default/mt_beca/images/new_homepage/reds_icon.jpg"></div>
      <p>The unique blend of herbs found in Ecstacy Red Cigarettes provides the smoker with a full-flavored, traditional tobacco-like aroma and taste.</p>
      <p><b>Ultras:</b></p>
      <div style="text-align:center;"><img src="http://www.ecstacycigarettes.com/skin/frontend/default/mt_beca/images/new_homepage/ultras_icon.jpg" ></div>
      <p>Ecstacy Cigarettes Ultra blend is the newest edition to the Ecstacy Cigarettes family, and is made from a unique blend of exotic herbs to produce a smooth and relaxing smoke.</p>
      <p><b>Menthol:</b></p>
      <div style="text-align:center;"><img src="http://www.ecstacycigarettes.com/skin/frontend/default/mt_beca/images/new_homepage/menthols_icon.jpg"></div>
      <p>Manufactured with the same herbal blend as the Reds and Whites, Ecstacy Menthol Cigarettes have just a touch of menthol added.</p>
      <p><b>Cannabis-Free:</b></p>
      <div style="text-align:center;"><img src="http://www.ecstacycigarettes.com/skin/frontend/default/mt_beca/images/new_homepage/cannabisfree_icon.jpg"></div>
      <p>While Ecstacy Cannabis-Free Cigarettes may feel, smell, and taste like the "real thing", this unique herbal blend is 100% legal and contains absolutely no THC.</p>
      </div>      
   </li>  
   <li>
   	<div class="quiz-link-outer"><a href="http://www.vapornation.com/prodguide/learning-center/quiz?chapter=10" class="quiz-link">Click Here to Take the Chapter Ten Quiz</a></div>

   </li> 
</ul>